version: '3.3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=2002
      - POSTGRES_USER=josue
      - POSTGRES_DB=my_store
    ports:
      - 5432:5432
    volumes:
      - /src/postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80